repos:

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort
      exclude: '^.*migrations.*$'

- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
    - id: black
      args: [--line-length=100, --safe]
      exclude: '^.*migrations.*$'

- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: debug-statements
    - id: flake8
      exclude: '^.*migrations.*$'
      additional_dependencies: [
        'flake8-blind-except',
        'flake8-comprehensions',
        'flake8-pep3101',
        'flake8-debugger'
      ]
